### ISSUE TITLE
Doesnt update

### ISSUE THREAD

**Issue by dwhacks** [ok2cqr/cqrprop#1]
I've installed this with your PPA on Linux Mint.
Everything seems fine, but it never updates. The only way I can seem to get it to update is to go into the location where it saves the image and delete the image.

Any idea what I can do? is this a permissions thing?

**Comment by ok2cqr** [comment]
I just did some updates to source code. Could you try it again, please? Thanks a lot.

**Comment by dwhacks** [comment]
Do I need to install from course? upgrading from apt says its at the newest version.

**Comment by ok2cqr** [comment]
Yes, you have to build it from source code. I tried to publish new version but build on Launchpad ended with access violation in Lazarus :(.

**Comment by dwhacks** [comment]
Do I need to install from course? upgrading from apt says its at the newest version.

**Comment by dwhacks** [comment]
Ok, I have installed it from sourse, without errors, last night. It is still on the same information, and when I right click -> refresh, it doesn't change. 

Could this be a permissions thing in the .config/cqrprop folder?
One strange thing, all the files in that folder say they were updated at the time that I did the refresh.

**Comment by dwhacks** [comment]
Well I've finally solved this, and it was no fault of yours! for some reason, my router was caching the image file, and thus it only changed when that file was purged from the cache. I added hamqsl to the do not cache list and all is well.

Finally I can use this great program!!!!
